// src/app/components/project-card/project-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-project-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './project-card.component.html',
  styleUrl: './project-card.component.css'
})
export class ProjectCardComponent {
  @Input() imageURL: string = "";
  @Input() title: string = "";
  @Input() description: string = "";
  @Input() technologies: string[] = [];
  @Input() source: string = "";

  getImageUrl(): string {
    return new URL(this.imageURL, import.meta.url).toString();
  }
}

<div class="card">
  <a [href]="getImageUrl()" target="_blank">
    <img src="{{imageURL}}" class="card-img-top" alt="Project Image">
  </a>
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
      <p class="card-text">{{ description }}</p>
      <div class="technologies">
        <span *ngFor="let technology of technologies" class="badge bg-secondary">{{ technology }}</span>
      </div>
      <br>
      @if (source !== "") {
        <a href="{{source}}">View Source</a>
      }@else {
        <a href="{{source}}">{{source}}</a>
      }
    </div>
</div>

// vue/src/components/ProjectCardComponent.vue
<script>
export default {
  name: 'ProjectCard',
  props: {
    imageUrl: {
      type: String,
      required: true
    },
    title: {
      type: String,
      required: true
    },
    description: {
      type: String,
      required: true
    },
    technologies: {
      type: Array,
      required: true
    },
    source: {
      type: String,
      required: false
    }
  },

  methods: {
    getImageUrl() {
    // This path must be correct for your file
    return new URL(`../assets/projects/${this.imageUrl}`, import.meta.url)
    }
  }
}
</script>

<template>
  <div class="card">
    <a :href="getImageUrl()" target="_blank">
      <img :src="getImageUrl()" class="card-img-top" alt="Project Image">
    </a>
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
      <p class="card-text">{{ description }}</p>
      <div class="technologies">
        <span v-for="technology in technologies" :key="technology" class="badge bg-secondary">{{ technology }}</span>
      </div>
      <br>
      <a v-if="source" href="https://drive.google.com/file/d/1l91F5gM8ztTe-moAwJr9ZhFrlsiNgogG/view?usp=sharing">Demo</a>
    </div>
  </div>
</template>

<style scoped>
.card {
  width:auto;
}

.card-img-top {
  height: 15rem;
  object-fit:fill;
}

.technologies {
  margin-top: 10px;
}

.badge {
  margin-right: 5px;
}
</style>
