// src/app/core/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {
  getFormEndpoint: string = "https://getform.io/f/05681971-283c-40ad-9c6b-b116b15df570"
}

<div class="container mt-5 mb-5 text-center">
    <h2>Interested in Working Together?</h2>
    <p class="text-muted">
    Please fill out the form below and let's chat!
    </p>
  <div class="row justify-content-center">
    <form action="{{getFormEndpoint}}" method="POST" class="col-md-7">
      <div class="form-group">
        <input
          type="text"
          name="name"
          placeholder="Name"
          class="form-control my-2"
          required
        />
      </div>
      <div class="form-group">
        <input
          type="text"
          name="email"
          placeholder="Email"
          class="form-control my-2"
          required
        />
      </div>
      <div class="form-group">
        <textarea
          name="message"
          placeholder="Message"
          rows="10"
          class="form-control my-2"
          required
        ></textarea>
      </div>
      <button
        type="submit"
        class="btn btn-primary btn-block my-4"
      >
        Submit
      </button>
    </form>
  </div>
</div>

// src/components/ContactComponent.vue
<script>

</script>

<template>
    <div class="container mt-5 text-center">
        <h2>Contact Me</h2>
        <p class="text-muted">
        Please fill out the form below
        </p>
      <div class="row justify-content-center">
        <form action="https://getform.io/f/05681971-283c-40ad-9c6b-b116b15df570" method="POST" class="col-md-7">
          <div class="form-group">
            <input
              type="text"
              name="name"
              placeholder="Name"
              class="form-control my-2"
              required
            />
          </div>
          <div class="form-group">
            <input
              type="text"
              name="email"
              placeholder="Email"
              class="form-control my-2"
              required
            />
          </div>
          <div class="form-group">
            <textarea
              name="message"
              placeholder="Message"
              rows="10"
              class="form-control my-2"
              required
            ></textarea>
          </div>
          <button
            type="submit"
            class="btn btn-primary btn-block my-4"
          >
            Submit
          </button>
        </form>
      </div>
    </div>
</template>
